services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://lilysewmi:butter1@cluster0.1hxi6vq.mongodb.net/ecotrack?retryWrites=true&w=majority&appName=Cluster0
    command: npm start
