# fly.toml app configuration file generated for ecotrackapp on 2025-04-22T01:07:34+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecotrackapp'
primary_region = 'bom'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[services.healthy_checks]
path = "/api/health"
interval = "30s"
