name: Daily DB Backup

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:     # Manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Create DB Snapshot
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_APP }}
        run: ~/.fly/bin/flyctl postgres snapshot create

