name: Daily DB Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:      # Manual trigger support

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install Fly CLI
        uses: superfly/flyctl-actions@1.3

      - name: Authenticate Fly CLI
        run: flyctl auth token ${{ secrets.FLY_API_KEY }}

      - name: Create Snapshot
        run: flyctl pg create snapshot ecotrack-db-v2
