name: Deploy to Fly.io

on:
 workflow_dispatch:
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Flyctl (Fly.io CLI)
      - name: Set up Flyctl
        uses: superfly/flyctl-actions@1.3
        with:
          flyctl_version: "latest"

      # Set up the API token for Fly.io
      - name: Set up Fly API token
        run: echo "${{ secrets.FLY_API_TOKEN }}" | flyctl auth login --token

      # Deploy the app to Fly.io (specifying the config file path)
      - name: Deploy to Fly.io
        run: |
          flyctl deploy --config ./backendfolder/fly.toml --build-only
