name: Deploy to Fly.io

on:
  workflow_dispatch:  # Lets you trigger it manually
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: dev
            app: ecotrackapp-dev
            token: FLY_API_TOKEN_DEV
          - branch: staging
            app: ecotrackapp-staging
            token: FLY_API_TOKEN_STAGING
          - branch: prod
            app: ecotrackapp-prod
            token: FLY_API_TOKEN_PROD

    if: github.ref_name == matrix.branch  # Only run for the matching environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --remote-only --config ./backend/fly.toml --app ${{ matrix.app }}"
        env:
          FLY_API_TOKEN: ${{ secrets[matrix.token] }}
