name: Deploy to Fly.io

on:
  push:
    branches:
      - dev
      - staging
      - prod  # Changed from 'main' to 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Deployment Environment
        run: |
          if [[ "${{ github.ref_name }}" == "prod" ]]; then  # Use 'prod' instead of 'main'
            echo "FLY_TOKEN_NAME=FLY_API_TOKEN_PROD" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "FLY_TOKEN_NAME=FLY_API_TOKEN_STAGING" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "FLY_TOKEN_NAME=FLY_API_TOKEN_DEV" >> $GITHUB_ENV
          else
            echo "Unknown environment: ${{ github.ref_name }}"
            exit 1
          fi

      - name: Display Deployment Environment
        run: |
          echo "Deploying to ${{ github.ref_name }}"

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.3
        with:
          args: deploy --app ${{ github.ref_name == 'prod' && 'ecotrackapp-prod' || github.ref_name == 'staging' && 'ecotrackapp-staging' || github.ref_name == 'dev' && 'ecotrackapp-dev' }}
        env:
          FLY_API_TOKEN: ${{ secrets[env.FLY_TOKEN_NAME] }}
