on:
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --app ecotrackapp-${{ github.ref_name }} --dockerfile ./backend/Dockerfile"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
