name: Deploy to Fly.io

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Display Deployment Environment
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Deploying to Production"
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "Deploying to Staging"
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "Deploying to Development"
          else
            echo "Unknown environment: ${{ github.ref_name }}"
          fi

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.3
        with:
          args: >
            deploy --app ${{ 
              github.ref_name == 'main' && 'ecotrackapp-prod' || 
              github.ref_name == 'staging' && 'ecotrackapp-staging' || 
              github.ref_name == 'dev' && 'ecotrackapp-dev' 
            }}
        env:
          FLY_API_TOKEN: ${{ secrets.flytoken }}
