name: Deploy to Fly.io

on:
  push:
    branches:
      - prod
      - staging
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set environment variables based on branch
      - name: Set environment variables based on branch
        id: set-env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "prod" ]]; then
            echo "FLY_APP=ecotrackapp-prod" >> $GITHUB_ENV
            echo "FLY_TOKEN_NAME=prod" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
            echo "FLY_APP=ecotrackapp-staging" >> $GITHUB_ENV
            echo "FLY_TOKEN_NAME=staging" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "FLY_APP=ecotrackapp-dev" >> $GITHUB_ENV
            echo "FLY_TOKEN_NAME=dev" >> $GITHUB_ENV
          else
            echo "Unknown branch: ${GITHUB_REF_NAME}"
            exit 1
          fi

      # Show deployment target
      - name: Show deployment target
        run: echo "Deploying $FLY_APP using token $FLY_TOKEN_NAME"

      # Deploy to Fly.io
      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --remote-only --config ./backend/fly.toml --app ${{ env.FLY_APP }}"
        env:
          FLY_API_TOKEN: ${{ secrets['FLY_API_TOKEN_' + env.FLY_TOKEN_NAME | upper] }}
