name: Deploy to Fly.io

on:
  push:
    branches:
      - prod
      - dev
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [[ "${GITHUB_REF_NAME}" == "prod" ]]; then
            echo "APP_NAME=ecotrackapp" >> $GITHUB_ENV
            echo "FLY_SECRET_NAME=FLY_API_TOKEN_PROD" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
            echo "APP_NAME=ecotrackapp-staging" >> $GITHUB_ENV
            echo "FLY_SECRET_NAME=FLY_API_TOKEN_STAGING" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "APP_NAME=ecotrackapp-dev" >> $GITHUB_ENV
            echo "FLY_SECRET_NAME=FLY_API_TOKEN_DEV" >> $GITHUB_ENV
          fi

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --remote-only --config ./backend/fly.toml --app ${{ env.APP_NAME }}"
        env:
          FLY_API_TOKEN: ${{ secrets[env.FLY_SECRET_NAME] }}
